name: Caller
on:
  push:
    paths:
      - '.github/workflows/caller.yml'
permissions:
  contents: read
jobs:
  call-reusable:
    uses: giga-gap-bb/bb-test-repo/.github/workflows/reusable-oidc.yml@main
